services:
  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_started
    ports:
      - 127.0.0.1:8000:8000
    environment:
      REDIS_URL: "redis://db"
    env_file:
      - path: "settings.env"
        required: true
  db:
    image: redis:latest
    restart: always

