from .blesk import BleskEstablishment
from .toni import ToniEstablishment
from .boasi import BoasiEstablishment
from .paleta import PaletaEstablishment
from .hodonanka import HodonankaEstablishment
from .pastafidli import PastaFidliEstablishment
from .mbrestaurace import MBRestauraceEstablishment
from .phobo import PhoboEstablishment
from .tajmahal import TajMahalEstablishment